In [2]:
%pip install nba_api

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nba_api in c:\users\vishn\appdata\roaming\python\python313\site-packages (1.11.4)
Requirement already satisfied: numpy>=2.1.0 in c:\programdata\anaconda3\lib\site-packages (from nba_api) (2.3.5)
Requirement already satisfied: pandas>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from nba_api) (2.3.3)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in c:\programdata\anaconda3\lib\site-packages (from nba_api) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2025.11.12)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.2.0->nba_api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.2.0->nba_api) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.2.0->nba_api) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->nba_api) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from nba_api.stats.endpoints import leaguegamefinder

In [5]:
gamefinder = leaguegamefinder.LeagueGameFinder(date_from_nullable='01/31/2020', league_id_nullable='00')
games = gamefinder.get_data_frames()[0]
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22025,1610612765,DET,Detroit Pistons,0022500978,2026-03-15,DET @ TOR,L,240,108,...,0.667,13,26,39,23,6,5,13,26,-11.0
1,22025,1610612761,TOR,Toronto Raptors,0022500978,2026-03-15,TOR vs. DET,W,240,119,...,0.767,20,28,48,25,9,5,10,20,11.0
2,22025,1610612755,PHI,Philadelphia 76ers,0022500980,2026-03-15,PHI vs. POR,W,240,109,...,0.933,14,37,51,17,13,4,12,19,6.0
3,22025,1610612750,MIN,Minnesota Timberwolves,0022500976,2026-03-15,MIN @ OKC,L,241,103,...,0.727,8,38,46,18,5,5,22,19,-13.0
4,22025,1610612757,POR,Portland Trail Blazers,0022500980,2026-03-15,POR @ PHI,L,240,103,...,0.667,15,34,49,26,6,9,18,14,-6.0

In [6]:
games.columns

Index(['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'PTS', 'FGM', 'FGA', 'FG_PCT',
       'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB',
       'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PLUS_MINUS'],
      dtype='object')

In [7]:
games=games[['TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'PLUS_MINUS']]

In [8]:
games

,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,PLUS_MINUS
0,Detroit Pistons,0022500978,2026-03-15,DET @ TOR,L,-11.0
1,Toronto Raptors,0022500978,2026-03-15,TOR vs. DET,W,11.0
2,Philadelphia 76ers,0022500980,2026-03-15,PHI vs. POR,W,6.0
3,Minnesota Timberwolves,0022500976,2026-03-15,MIN @ OKC,L,-13.0
4,Portland Trail Blazers,0022500980,2026-03-15,POR @ PHI,L,-6.0
...,...,...,...,...,...,...
16719,New Orleans Pelicans,0021900723,2020-01-31,NOP vs. MEM,W,28.0
16720,Brooklyn Nets,0021900721,2020-01-31,BKN vs. CHI,W,15.0
16721,Oklahoma City Thunder,0021900725,2020-01-31,OKC @ PHX,W,4.0
16722,Chicago Bulls,0021900721,2020-01-31,CHI @ BKN,L,-15.0
16723,Phoenix Suns,0021900725,2020-01-31,PHX vs. OKC,L,-4.0

In [ ]:
# Final DataFrame: one row for ne game
# two columns: 1.result of game: target 2.score stat comparing two teams: feature

In [9]:
import pandas as pd

In [10]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16724 entries, 0 to 16723
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   TEAM_NAME   16724 non-null  object
 1   GAME_ID     16724 non-null  object
 2   GAME_DATE   16724 non-null  object
 3   MATCHUP     16724 non-null  object
 4   WL          16720 non-null  object
 5   PLUS_MINUS  16724 non-null  float64
dtypes: float64(1), object(5)
memory usage: 784.1+ KB

In [11]:
games = games.sort_values('GAME_DATE')

In [12]:
games

,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,PLUS_MINUS
16723,Phoenix Suns,0021900725,2020-01-31,PHX vs. OKC,L,-4.0
16710,Denver Nuggets,0021900724,2020-01-31,DEN @ MIL,W,12.0
16711,Milwaukee Bucks,0021900724,2020-01-31,MIL vs. DEN,L,-12.0
16712,Portland Trail Blazers,0021900726,2020-01-31,POR @ LAL,W,8.0
16713,Los Angeles Lakers,0021900726,2020-01-31,LAL vs. POR,L,-8.0
...,...,...,...,...,...,...
11,Golden State Warriors,0022500981,2026-03-15,GSW @ NYK,L,-3.0
12,Cleveland Cavaliers,0022500977,2026-03-15,CLE vs. DAL,L,-10.0
13,Oklahoma City Thunder,0022500976,2026-03-15,OKC vs. MIN,W,13.0
7,Sacramento Kings,0022500982,2026-03-15,SAC vs. UTA,W,5.0
0,Detroit Pistons,0022500978,2026-03-15,DET @ TOR,L,-11.0

In [13]:
games['avg_30_plus_minus'] = games.groupby('TEAM_NAME')['PLUS_MINUS'].transform(lambda x: x.rolling(30, closed='left').mean())

In [14]:
games[games['TEAM_NAME']=='Toronto Raptors'].head(35)

,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,PLUS_MINUS,avg_30_plus_minus
16717,Toronto Raptors,0021900720,2020-01-31,TOR @ DET,W,13.0,NaN
16689,Toronto Raptors,0021900740,2020-02-02,TOR vs. CHI,W,27.0,NaN
16653,Toronto Raptors,0021900758,2020-02-05,TOR vs. IND,W,1.0,NaN
16613,Toronto Raptors,0021900772,2020-02-07,TOR @ IND,W,9.0,NaN
16607,Toronto Raptors,0021900781,2020-02-08,TOR vs. BKN,W,1.0,NaN
16562,Toronto Raptors,0021900796,2020-02-10,TOR vs. MIN,W,11.0,NaN
16538,Toronto Raptors,0021900809,2020-02-12,TOR @ BKN,L,-10.0,NaN
16499,Toronto Raptors,0021900829,2020-02-21,TOR vs. PHX,W,17.0,NaN
16463,Toronto Raptors,0021900843,2020-02-23,TOR vs. IND,W,46.0,NaN
16430,Toronto Raptors,0021900858,2020-02-25,TOR vs. MIL,L,-11.0,NaN
16399,Toronto Raptors,0021900879,2020-02-28,TOR vs. CHA,L,-3.0,NaN
16364,Toronto Raptors,0021900898,2020-03-01,TOR @ DEN,L,-15.0,NaN
16327,Toronto Raptors,0021900914,2020-03-03,TOR @ PHX,W,9.0,NaN
16301,Toronto Raptors,0021900929,2020-03-05,TOR @ GSW,W,8.0,NaN
16247,Toronto Raptors,0021900956,2020-03-08,TOR @ SAC,W,5.0,NaN
16242,Toronto Raptors,0021900959,2020-03-09,TOR @ UTA,W,9.0,NaN
16194,Toronto Raptors,0011900111,2020-07-24,TOR vs. HOU,W,11.0,NaN
16172,Toronto Raptors,0011900121,2020-07-26,TOR vs. POR,W,6.0,NaN
16157,Toronto Raptors,0011900129,2020-07-28,TOR @ PHX,L,-11.0,NaN
16125,Toronto Raptors,0021901243,2020-08-01,TOR vs. LAL,W,15.0,NaN
16107,Toronto Raptors,0021901250,2020-08-03,TOR @ MIA,W,4.0,NaN
16081,Toronto Raptors,0021901266,2020-08-05,TOR @ ORL,W,10.0,NaN
16057,Toronto Raptors,0021901279,2020-08-07,TOR vs. BOS,L,-22.0,NaN
16030,Toronto Raptors,0021901286,2020-08-09,TOR vs. MEM,W,9.0,NaN
16022,Toronto Raptors,0021901294,2020-08-10,TOR @ MIL,W,8.0,NaN
15999,Toronto Raptors,0021901305,2020-08-12,TOR @ PHI,W,4.0,NaN
15975,Toronto Raptors,0021901318,2020-08-14,TOR vs. DEN,W,8.0,NaN
15965,Toronto Raptors,0041900111,2020-08-17,TOR vs. BKN,W,24.0,NaN
15950,Toronto Raptors,0041900112,2020-08-19,TOR vs. BKN,W,5.0,NaN
15931,Toronto Raptors,0041900113,2020-08-21,TOR @ BKN,W,25.0,NaN
15916,Toronto Raptors,0041900114,2020-08-23,TOR @ BKN,W,28.0,7.100000
15893,Toronto Raptors,0041900211,2020-08-30,TOR vs. BOS,L,-18.0,7.600000
15883,Toronto Raptors,0041900212,2020-09-01,TOR vs. BOS,L,-3.0,6.100000
15872,Toronto Raptors,0041900213,2020-09-03,TOR @ BOS,W,1.0,5.966667
15865,Toronto Raptors,0041900214,2020-09-05,TOR @ BOS,W,7.0,5.700000

In [15]:
msk = games['MATCHUP'].str.contains('@')

In [16]:
games_away = games[msk]
games_home = games[~msk]

In [17]:
games_home.shape

(8342, 7)

In [18]:
games_home

,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,PLUS_MINUS,avg_30_plus_minus
16723,Phoenix Suns,0021900725,2020-01-31,PHX vs. OKC,L,-4.0,NaN
16711,Milwaukee Bucks,0021900724,2020-01-31,MIL vs. DEN,L,-12.0,NaN
16713,Los Angeles Lakers,0021900726,2020-01-31,LAL vs. POR,L,-8.0,NaN
16714,Houston Rockets,0021900722,2020-01-31,HOU vs. DAL,W,7.0,NaN
16720,Brooklyn Nets,0021900721,2020-01-31,BKN vs. CHI,W,15.0,NaN
...,...,...,...,...,...,...,...
5,Milwaukee Bucks,0022500979,2026-03-15,MIL vs. IND,W,11.0,-8.733333
8,New York Knicks,0022500981,2026-03-15,NYK vs. GSW,W,3.0,8.666667
12,Cleveland Cavaliers,0022500977,2026-03-15,CLE vs. DAL,L,-10.0,6.966667
13,Oklahoma City Thunder,0022500976,2026-03-15,OKC vs. MIN,W,13.0,7.300000
7,Sacramento Kings,0022500982,2026-03-15,SAC vs. UTA,W,5.0,-7.000000

In [19]:
games_away

,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,PLUS_MINUS,avg_30_plus_minus
16710,Denver Nuggets,0021900724,2020-01-31,DEN @ MIL,W,12.0,NaN
16712,Portland Trail Blazers,0021900726,2020-01-31,POR @ LAL,W,8.0,NaN
16715,Dallas Mavericks,0021900722,2020-01-31,DAL @ HOU,L,-7.0,NaN
16722,Chicago Bulls,0021900721,2020-01-31,CHI @ BKN,L,-15.0,NaN
16717,Toronto Raptors,0021900720,2020-01-31,TOR @ DET,W,13.0,NaN
...,...,...,...,...,...,...,...
6,Dallas Mavericks,0022500977,2026-03-15,DAL @ CLE,W,10.0,-6.633333
9,Utah Jazz,0022500982,2026-03-15,UTA @ SAC,L,-5.0,-8.400000
10,Indiana Pacers,0022500979,2026-03-15,IND @ MIL,L,-11.0,-8.333333
11,Golden State Warriors,0022500981,2026-03-15,GSW @ NYK,L,-3.0,0.266667
0,Detroit Pistons,0022500978,2026-03-15,DET @ TOR,L,-11.0,8.966667

In [20]:
games

,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,PLUS_MINUS,avg_30_plus_minus
16723,Phoenix Suns,0021900725,2020-01-31,PHX vs. OKC,L,-4.0,NaN
16710,Denver Nuggets,0021900724,2020-01-31,DEN @ MIL,W,12.0,NaN
16711,Milwaukee Bucks,0021900724,2020-01-31,MIL vs. DEN,L,-12.0,NaN
16712,Portland Trail Blazers,0021900726,2020-01-31,POR @ LAL,W,8.0,NaN
16713,Los Angeles Lakers,0021900726,2020-01-31,LAL vs. POR,L,-8.0,NaN
...,...,...,...,...,...,...,...
11,Golden State Warriors,0022500981,2026-03-15,GSW @ NYK,L,-3.0,0.266667
12,Cleveland Cavaliers,0022500977,2026-03-15,CLE vs. DAL,L,-10.0,6.966667
13,Oklahoma City Thunder,0022500976,2026-03-15,OKC vs. MIN,W,13.0,7.300000
7,Sacramento Kings,0022500982,2026-03-15,SAC vs. UTA,W,5.0,-7.000000
0,Detroit Pistons,0022500978,2026-03-15,DET @ TOR,L,-11.0,8.966667

In [21]:
games_merged = pd.merge(games_home, games_away, on='GAME_ID', suffixes=('_home', '_away'))

In [22]:
games_merged

,TEAM_NAME_home,GAME_ID,GAME_DATE_home,MATCHUP_home,WL_home,PLUS_MINUS_home,avg_30_plus_minus_home,TEAM_NAME_away,GAME_DATE_away,MATCHUP_away,WL_away,PLUS_MINUS_away,avg_30_plus_minus_away
0,Phoenix Suns,0021900725,2020-01-31,PHX vs. OKC,L,-4.0,NaN,Oklahoma City Thunder,2020-01-31,OKC @ PHX,W,4.0,NaN
1,Milwaukee Bucks,0021900724,2020-01-31,MIL vs. DEN,L,-12.0,NaN,Denver Nuggets,2020-01-31,DEN @ MIL,W,12.0,NaN
2,Los Angeles Lakers,0021900726,2020-01-31,LAL vs. POR,L,-8.0,NaN,Portland Trail Blazers,2020-01-31,POR @ LAL,W,8.0,NaN
3,Houston Rockets,0021900722,2020-01-31,HOU vs. DAL,W,7.0,NaN,Dallas Mavericks,2020-01-31,DAL @ HOU,L,-7.0,NaN
4,Brooklyn Nets,0021900721,2020-01-31,BKN vs. CHI,W,15.0,NaN,Chicago Bulls,2020-01-31,CHI @ BKN,L,-15.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8340,Milwaukee Bucks,0022500979,2026-03-15,MIL vs. IND,W,11.0,-8.733333,Indiana Pacers,2026-03-15,IND @ MIL,L,-11.0,-8.333333
8341,New York Knicks,0022500981,2026-03-15,NYK vs. GSW,W,3.0,8.666667,Golden State Warriors,2026-03-15,GSW @ NYK,L,-3.0,0.266667
8342,Cleveland Cavaliers,0022500977,2026-03-15,CLE vs. DAL,L,-10.0,6.966667,Dallas Mavericks,2026-03-15,DAL @ CLE,W,10.0,-6.633333
8343,Oklahoma City Thunder,0022500976,2026-03-15,OKC vs. MIN,W,13.0,7.300000,Minnesota Timberwolves,2026-03-15,MIN @ OKC,L,-13.0,1.033333
8344,Sacramento Kings,0022500982,2026-03-15,SAC vs. UTA,W,5.0,-7.000000,Utah Jazz,2026-03-15,UTA @ SAC,L,-5.0,-8.400000

In [23]:
games_merged['avg_30_plus_minus_diff']=games_merged['avg_30_plus_minus_home']-games_merged['avg_30_plus_minus_away']

In [24]:
games_merged

,TEAM_NAME_home,GAME_ID,GAME_DATE_home,MATCHUP_home,WL_home,PLUS_MINUS_home,avg_30_plus_minus_home,TEAM_NAME_away,GAME_DATE_away,MATCHUP_away,WL_away,PLUS_MINUS_away,avg_30_plus_minus_away,avg_30_plus_minus_diff
0,Phoenix Suns,0021900725,2020-01-31,PHX vs. OKC,L,-4.0,NaN,Oklahoma City Thunder,2020-01-31,OKC @ PHX,W,4.0,NaN,NaN
1,Milwaukee Bucks,0021900724,2020-01-31,MIL vs. DEN,L,-12.0,NaN,Denver Nuggets,2020-01-31,DEN @ MIL,W,12.0,NaN,NaN
2,Los Angeles Lakers,0021900726,2020-01-31,LAL vs. POR,L,-8.0,NaN,Portland Trail Blazers,2020-01-31,POR @ LAL,W,8.0,NaN,NaN
3,Houston Rockets,0021900722,2020-01-31,HOU vs. DAL,W,7.0,NaN,Dallas Mavericks,2020-01-31,DAL @ HOU,L,-7.0,NaN,NaN
4,Brooklyn Nets,0021900721,2020-01-31,BKN vs. CHI,W,15.0,NaN,Chicago Bulls,2020-01-31,CHI @ BKN,L,-15.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8340,Milwaukee Bucks,0022500979,2026-03-15,MIL vs. IND,W,11.0,-8.733333,Indiana Pacers,2026-03-15,IND @ MIL,L,-11.0,-8.333333,-0.400000
8341,New York Knicks,0022500981,2026-03-15,NYK vs. GSW,W,3.0,8.666667,Golden State Warriors,2026-03-15,GSW @ NYK,L,-3.0,0.266667,8.400000
8342,Cleveland Cavaliers,0022500977,2026-03-15,CLE vs. DAL,L,-10.0,6.966667,Dallas Mavericks,2026-03-15,DAL @ CLE,W,10.0,-6.633333,13.600000
8343,Oklahoma City Thunder,0022500976,2026-03-15,OKC vs. MIN,W,13.0,7.300000,Minnesota Timberwolves,2026-03-15,MIN @ OKC,L,-13.0,1.033333,6.266667
8344,Sacramento Kings,0022500982,2026-03-15,SAC vs. UTA,W,5.0,-7.000000,Utah Jazz,2026-03-15,UTA @ SAC,L,-5.0,-8.400000,1.400000

In [25]:
games_model = games_merged[['WL_home', 'avg_30_plus_minus_diff']].dropna()

In [26]:
games_model['WL_home'] = games_model['WL_home'].map({'W':1, 'L':0})

In [27]:
games_model

      WL_home  avg_30_plus_minus_diff
398         0               -5.366667
399         0               -6.233333
401         1                1.933333
402         1               -4.333333
403         0               -8.066667
...       ...                     ...
8340        1               -0.400000
8341        1                8.400000
8342        0               13.600000
8343        1                6.266667
8344        1                1.400000

[7784 rows x 2 columns]

In [ ]:
# Build a Predictive Model

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
df_train, df_test = train_test_split(games_model, stratify = games_model['WL_home'], test_size=0.2, random_state=7)

In [30]:
df_train.shape

(6227, 2)

In [31]:
df_test.shape

(1557, 2)

In [32]:
target = 'WL_home'
X_train = df_train.drop(columns=target) # avg_plus_minus_diff
y_train = df_train[target] # WL_home

X_test = df_test.drop(columns=target) # avg_plus_minus_diff
y_test = df_test[target] # WL_home

In [ ]:
#pip install xgboost

In [33]:
from sklearn.preprocessing import LabelEncoder
import xgboost as xgb

In [34]:
le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)

In [35]:
clf = xgb.XGBClassifier(random_state=7)

In [36]:
clf.fit(X_train, y_train_encoded)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [37]:
from sklearn.metrics import accuracy_score
y_pred = clf.predict(X_test)

In [38]:
accuracy_score(y_test, y_pred)

0.5998715478484264

In [39]:
# Hyperparameter tuning - random search

from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import loguniform

In [40]:
hyp_params = {'learning_rate' : loguniform(0.0001,1),
              'max_depth' : [2,3,4,5,6,7,8,9],
              'subsample': [0.7,0.8,0.9,1.0],
              'n_estimators' : [50,100,150,200]}

In [41]:
random_hyp = RandomizedSearchCV(estimator=clf,
                                param_distributions=hyp_params,
                                n_iter=20,
                                cv=7,
                                scoring='accuracy',
                                random_state=7)

In [42]:
random_hyp.fit(X_train, y_train)

RandomizedSearchCV(cv=7,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           callbacks=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None, device=None,
                                           early_stopping_rounds=None,
                                           enable_categorical=False,
                                           eval_metric=None, feature_types=None,
                                           feature_weights=None, gamma=None,
                                           grow_policy=None,
                                           importance_type=None,
                                           interaction_constrain...
                                           monotone_constraints=None,
                                           multi_strategy=None,
                                           n_estimators=None, n_jobs=None,
                                           num_parallel_tree=None, ...),
                   n_iter=20,
                   param_distributions={'learning_rate': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x0000027037812A50>,
                                        'max_depth': [2, 3, 4, 5, 6, 7, 8, 9],
                                        'n_estimators': [50, 100, 150, 200],
                                        'subsample': [0.7, 0.8, 0.9, 1.0]},
                   random_state=7, scoring='accuracy')

In [43]:
random_hyp.best_params_

{'learning_rate': np.float64(0.025246179740589205),
 'max_depth': 2,
 'n_estimators': 150,
 'subsample': 0.7}

In [46]:
model_hyp=random_hyp.best_estimator_

In [47]:
y_pred_hyp=model_hyp.predict(X_test)

In [48]:
accuracy_score(y_test, y_pred_hyp)

0.6255619781631342

In [49]:
from joblib import dump, load

In [50]:
dump(model_hyp, 'model_nba.joblib')

['model_nba.joblib']

In [51]:
model_saved = load('model_nba.joblib')

In [52]:
accuracy_score(y_test, model_saved.predict(X_test))

0.6255619781631342

In [ ]:
#home team away team -> game results

In [53]:
team_home = 'Toronto Raptors'
team_away = 'Boston Celtics'

In [65]:
def predict_games(team_home, team_away):
    
    from nba_api.stats.endpoints import leaguegamefinder
    
    gamefinder = leaguegamefinder.LeagueGameFinder(date_from_nullable='01/31/2020', league_id_nullable='00')
    games = gamefinder.get_data_frames()[0]
    
    games=games[['TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'PLUS_MINUS']]
    
    import pandas as pd
    
    games['GAME_DATE'] = pd.to_datetime(games['GAME_DATE'])
    
    msk_home = (games['TEAM_NAME']==team_home)
    games_30_home=games[msk_home].sort_values('GAME_DATE').tail(30)
    home_plus_minus = games_30_home['PLUS_MINUS'].mean()
    
    msk_away = (games['TEAM_NAME']==team_away)
    games_30_away=games[msk_away].sort_values('GAME_DATE').tail(30)
    away_plus_minus = games_30_away['PLUS_MINUS'].mean()
    
    games_diff = home_plus_minus - away_plus_minus
    
    model_saved = load('model_nba.joblib')
    import numpy as np
    predict_home_win = model_saved.predict(np.array([games_diff]))[0]
    
    predict_winning_probability = model_saved.predict_proba(np.array([games_diff]))[0][1]

    return predict_home_win, predict_winning_probability

In [66]:
predict_games('Toronto Raptors', 'Boston Celtics')

(np.int64(0), np.float32(0.4154452))